# Generated by Django 6.1 on 2026-08-31 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_created_products_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='Зарезервировано')),
                ('warehouse_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Местоположение на складе')),
                ('last_restocked_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего пополнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Запас',
                'verbose_name_plural': 'Запасы',
                'db_table': 'inventory',
            },
        ),
    ]
