# Generated by Django 5.2.17 on 2026-09-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatistics',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('user_count', models.IntegerField(default=0)),
                ('event_count', models.IntegerField(default=0)),
                ('edited_events', models.IntegerField(default=0)),
                ('cancelled_events', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Статистика бота',
                'verbose_name_plural': 'Статистика бота',
                'db_table': 'bot_statistics',
                'ordering': ['-date'],
                'managed': False,
            },
        ),
    ]
