# Generated by Django 6.1 on 2026-08-28 17:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_change_clients_model'),
        ('products', '0001_created_products_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён'), ('refunded', 'Возврат')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая сумма')),
                ('shipping_street', models.CharField(max_length=100, verbose_name='Улица')),
                ('shipping_house_number', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('shipping_apartment', models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира')),
                ('shipping_city', models.CharField(max_length=50, verbose_name='Город')),
                ('shipping_postal_code', models.CharField(max_length=20, verbose_name='Почтовый индекс')),
                ('shipping_country', models.CharField(default='Россия', max_length=50, verbose_name='Страна')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Способ оплаты')),
                ('payment_status', models.CharField(default='pending', max_length=50, verbose_name='Статус оплаты')),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Трек-номер')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.clients', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена на момент покупки')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма скидки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'db_table': 'order_items',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='orders_client__2e756d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='orders_order_d_6e39a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
