# Generated by Django 6.1 on 2026-08-28 13:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(db_index=True, max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(db_index=True, max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'Пользователь с таким email уже зарегистрирован'}, max_length=100, unique=True, verbose_name='Email')),
                ('phone', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: +71234567890 (10-15 цифр)', regex='^\\+?[0-9]{10,15}$')], verbose_name='Телефон')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('apartment', models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира')),
                ('city', models.CharField(db_index=True, max_length=50, verbose_name='Город')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Почтовый индекс')),
                ('country', models.CharField(default='Russia', max_length=50, verbose_name='Страна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='clients_last_na_7dc725_idx'), models.Index(fields=['city'], name='clients_city_c00b7c_idx')],
            },
        ),
    ]
